package com.psajd.quizletBot.models.bot;

public enum BotState {
    ON_START,
    ON_PACK_CREATION_START,
    ON_PACK_CREATION_NAME,
    ON_PACK_UPDATE_NAME,
    ON_PACK_TABLE,
    ON_CHOOSE_PACK,
    ON_PACK_INFO,
    ON_PRACTICE,
    ON_CHECK_CORRECT_ANSWER,
    ON_SHOW_CARDS,
    ON_ADD_CARD_TERM,
    ON_ADD_CARD_DEFINITION,
    ON_REMOVE_CARD_PACK,
    ON_CARD_NAME_CHOICE;
}
